name: Criando nosso trigger Schedule

on:
  schedule:
    - cron: '27 00 * * 3'
    - cron: '*/5 * * * *'

jobs:
  executa-schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Informa Horário Específico com Cron Fixo
        if: github.event.schedule == '27 00 * * 3'
        run: echo "Esse step rodou pois essa execução foi pelo horário agendado"

      - name: Informa Horário
        run: echo "Nesse step passam todos os crons, agora são $(date) UTC"
