name: Primeiro Workflow

on:
  workflow_dispatch
jobs:
  giropops:
    runs-on: ubuntu-latest
    steps:
      - name: Confere versao do Ubunto
        run: cat /etc/os-release

      - name: Exibir Mensagem
        run: echo "Estou fazendo o curso de github Action"
