name: Primeiro Desafio

on: 
  workflow_dispatch:
    inputs:
       imagem:
        description: "Informe uma Imagem a ser Consultada"
        required: true
        type: string


jobs:
  desafio:
   runs-on: ubuntu-latest
   steps:
      - name: Baixando Imagem selecionada
        run: docker pull "${{ inputs.imagem }}"

      - name: Listar Imagens
        run: docker images

      - name: Instalar Docker Scout CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.s

      - name: Relatorio de Vulnerabilidade
        run: docker scout cves "${{ inputs.imagem }}"
