name: 03 - Publicacao

on:
  workflow_run:
    workflows:
      - "01 - Validando Ambiente"
    types:
      - completed

jobs:
  publicar:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Publicar
        run: |
          echo "Publicando aplicacao..."
