name: Trabalhando jobs compartilhando arquivo

on:
  push:
    branches:
      - main

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Confere versao do Ubunto
        run: cat /etc/os-release

      - name: Exibir Mensagem
        run: echo "Estou fazendo o curso de github Action" > ${{ github.workspace}}/mensagem.txt
      
      - uses: actions/upload-artifact@v4
        with:
          name: strigus-upload
          path: ${{ github.workspace }}/mensagem.txt


  job_2:
    runs-on: ubuntu-latest
    steps:
      - name: lista inicial
        run: ls -lha

      - uses: actions/download-artifact@v4
        with:
          name: strigus-upload
          path: strigus

      - name: Ver conteudo do diretorio
        run: ls -lha && ls ./strigus/
      
      - name: acessa arquivo mensagem
        run: mv strigus/mensagem.txt . && rm -rf ./strigus

      - name: lista apos mover e apagar pasta
        run: ls -lha

      - name: Acessa arquivo mensagem
        run: cat mensagem.txt
    





