name: Trabalhando steps

on:
  push:
    branches:
      - main

jobs:
  giropops:
    runs-on: ubuntu-latest
    steps:
      - name: Confere versao do Ubunto
        run: cat /etc/os-release

      - name: Exibir Mensagem
        run: echo "Estou fazendo o curso de github Action" > mensagem.txt
      
      - name: novo steps
        runs: ls - lha

      - name: Lendo arquivos
        run: cat mensagem.txt


