name: Criando nosso trigger gollum

on:
  gollum

jobs:
  job-gollum:
    runs-on: ubuntu-latest
    steps:
      - name: Printa gollum
        run: echo "Alguma alteração foi realizada na Wiki!"