name: Testando trigger delete

on:
  delete
    

jobs:
  print-delete-branch-or-tag:
    runs-on: ubuntu-latest
    steps:

      - name: Avisa quando branch ou tag deletada
        run: echo "Uma nova branch ou tag foi deletada"