name: Criando nosso trigger Push

on:
  push:
    branches:
      - 'main'
      - 'staging'
    paths:  
      - '**.tf'

jobs:
  job-push:
    runs-on: ubuntu-latest
    steps:
      - name: Printa Push
        run: echo "Um push em seus arquivos de Terraform foi feito em uma das branchs principais"